# Generated by Django 3.2 on 2021-05-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_db',
            name='auto_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inv_db',
            name='Asset_Name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
