# Generated by Django 3.2 on 2021-05-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210510_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_db',
            name='auto_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
