# Generated by Django 3.2 on 2021-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_inv_db_asset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASSETS',
            fields=[
                ('Asset_Name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
