# Generated by Django 3.2 on 2021-05-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_db',
            name='Asset_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ASSETS', to='application.assets'),
        ),
    ]
